### ISSUE TITLE
all testing marked skipped result

### ISSUE THREAD

**Issue by redkris** [pablosnt/rekono#32] opened 2022-09-05 16:11 UTC
I have managed to install rekono in ubuntu 20.04 using CLI, I am testing the whole scenario the the target local DVWA website but it seems all testing scenario skipped resulted, any ideas ?

**Comment by pablosnt** [comment] 2022-09-05 17:53
Hi @redkris, Skipped result occurs when the tool can't be executed because an input is needed and it's not found on the previous findings or in the targets. So can you share with me the definition of your target please? Moreover, the output of the command `systemctl status executions-worker-*` can be useful to check what is the parameter that causes the skipped result. By the time, I will try to reproduce your error

**Comment by pablosnt** [comment] 2022-09-05 19:08
Sorry @redkris, I forgot one important thing. Rekono doesn't include the supported hacking tools in its installation by default, do you install the hacking tools that do you want to execute using Rekono? With the CLI, you can use the command `rekono install --all-tools` to install both, Rekono and the hacking tools.

**Comment by pablosnt** [comment] 2022-09-20 12:18
I think the reason of this problem is that the hacking tools used by Rekono aren't installed on your system. Please review my previous comments to solve the problem. I close this ticket, please reopen it if the error persists.

**Closed by pablosnt** 2022-09-20 12:18 UTC
Labels: help wanted, question
