### ISSUE TITLE
Error during Vue Installation

### ISSUE THREAD

**Issue by gray-area** [pablosnt/rekono#165] opened 2023-02-22 15:20 UTC
When I run "rekono install", its gets as far as the "Vue" installation and then presents "Error during Vue Installation" and exits. Can you please provide any information on how to troubleshoot this?

**Comment by pablosnt** [comment] 2023-02-22 15:59
Hi, I think that the problem is like this one https://github.com/pablosnt/rekono-cli/issues/35, but during `Vue` installation? Can you try to install `Vue` by your own with `npm install -g @vue/cli` and retry please?

**Comment by gray-area** [comment] 2023-02-22 19:17
This took a while to fix, but the error came from requiring sudo  privs to install Vue. I cleaned up the rekono install, manually installed vue with sudo, then re-ran the rekono install command. It seems to be installing now. Thanks for the help!

**Comment by pablosnt** [comment] 2023-02-22 19:31
Great, you are welcome! I close the issue, please reopen it if you need it

**Closed by pablosnt** 2023-02-22 19:31 UTC
Labels: help wanted, question
