### ISSUE TITLE
Install in vmware, it doesent works

### ISSUE THREAD

**Issue by Flow44A** [pablosnt/rekono#251] opened 2023-09-28 09:34 UTC
**Describe your problem, your doubts or whatever you need**The following NEW packages will be installed:
  rekono-kbx
0 upgraded, 1 newly installed, 0 to remove and 192 not upgraded.
18 not fully installed or removed.
Need to get 101 kB of archives.
After this operation, 136 kB of additional disk space will be used.
Get:1 http://kali.download/kali kali-rolling/main amd64 rekono-kbx amd64 1.6.3 [101 kB]
Fetched 101 kB in 1s (112 kB/s)  
(Reading database ... 436831 files and directories currently installed.)
Preparing to unpack .../rekono-kbx_1.6.3_amd64.deb ...
Unpacking rekono-kbx (1.6.3) ...
dpkg: error processing archive /var/cache/apt/archives/rekono-kbx_1.6.3_amd64.deb (--unpack):
 trying to overwrite '/usr/share/icons/hicolor/16x16/apps/rekono.png', which is also in package kali-menu 2023.4.3
Errors were encountered while processing:
 /var/cache/apt/archives/rekono-kbx_1.6.3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by pablosnt** [comment] 2023-09-30 09:15
Hello @Flow44A,

Someone reported a similar issue some time ago, try to follow my answer to it, I hope it will work. The issue is this:  https://github.com/pablosnt/rekono/issues/249

Please let me know if the problem persists
Thanks!

**Comment by pablosnt** [comment] 2023-10-08 07:39
I'm closing this issue, please reopen it if the problem persists. Thank you!

**Closed by pablosnt** 2023-10-08 07:39 UTC
Labels: help wanted, question
