### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by ablito19** [pablosnt/rekono#33] opened 2022-09-06 11:11 UTC
Default login/password rekono/rekono not working after fresh install.
How to correct it

**Comment by pablosnt** [comment] 2022-09-06 11:19
How did you install Rekono? Using pip or Docker?

**Comment by ablito19** [comment] 2022-09-06 12:43
> How did you install Rekono? Using pip or Docker?

Using docker

**Comment by pablosnt** [comment] 2022-09-06 12:47
In that case, please ensure that the initializer node has been executed at least once, because this node performs the default user creation.

Moreover, you can reboot the backend and the nginx nodes, because sometimes connection error happens and the API requests don't reach the backend to perform the login.

Please tell me if this work for you

**Comment by pablosnt** [comment] 2022-09-06 13:50
I will check, but Docker installation work for me, I use it very often. Can you repeat the `docker-compose up - d` command please?

**Comment by ablito19** [comment] 2022-09-06 13:57
i try it again but no luck. Can i use command for create User ?

**Comment by pablosnt** [comment] 2022-09-06 14:01
Of course, you can do that. Get into the backend node and execute `python manage.py createsuperuser` from the /code directory. I hope this to be helpful

**Comment by ablito19** [comment] 2022-09-06 14:07
└─$ sudo python3 manage.py createsuperuser
Traceback (most recent call last):
  File "/home/xxx/rekono/rekono/manage.py", line 22, in <module>
    main()
  File "/home/xxx/rekono/rekono/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python3/dist-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_filters'

**Comment by ablito19** [comment] 2022-09-06 14:16
i install requirement manually but i get another errors.

sudo python3 manage.py createsuperuser
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/lib/python3/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python3/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/Tools/rekono/rekono/manage.py", line 22, in <module>
    main()
  File "/home/kali/Tools/rekono/rekono/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 397, in execute
    self.check_migrations()
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 486, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/lib/python3/dist-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/lib/python3/dist-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/lib/python3/dist-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/lib/python3/dist-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/lib/python3/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/lib/python3/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/lib/python3/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/lib/python3/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python3/dist-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

**Comment by pablosnt** [comment] 2022-09-06 16:07
Okay, before run it, execute the following commands to configure the database connection:

`export RKN_DB_HOST="postgres"`
`export RKN_DB_USER="postgres"`
`export RKN_DB_PASSWORD="postgres"`

**Comment by ablito19** [comment] 2022-09-07 11:20
i uninstall and remove all images and volumes in docker then reinstall the tool.
and i clone project in no-root folder before running install procedure. I dont know if it was the problem but it work now.

**Comment by pablosnt** [comment] 2022-09-07 13:22
Okay, perfect. I have seen this error before, during the development of Rekono. But I think that it's a puntual error, because I can't reproduce it and the error disappears when the images and volumes are regenerated. Anyway, I create this pull request #34 to ensure the dependencies between the containers. By the time, I close this issue, please reopen it if the error persists

**Closed by pablosnt** 2022-09-07 13:22 UTC
Labels: bug
